spring:
  application:
    name: service-two
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      username: admin
      password: admin
  profiles:
    active: ${profile}
server:
  port: 8082